= sick_visionary_cpp_shared

== Overview

This repository provides the base interfaces to access SICK Visionary devices.
Using the classes in this module parameters can be queried and configured, status information can be accessed
and 3D image data streams can be set up and controlled.

Supported protocols are
* CoLa-B for parametrization as used by the Visionary-T (CX/AG/DT) and Visionary-S devices.
* CoLa-2 for parametrization as used by the Visionary-T Mini device.
* the SICK Blob format for streaming data.


== Building

The module uses the https://cmake.org/[CMake] build system version 3.16 or higher.
Beside the standard options like https://cmake.org/cmake/help/v3.16/variable/CMAKE_BUILD_TYPE.html[`CMAKE_BUILD_TYPE`] for code generation and
the https://cmake.org/cmake/help/v3.16/module/GNUInstallDirs.html[installation directory options]
it supports the following additional CMake build options:

[cols="0m,4d,1d,0d"]
|===
| option name | description | values | default value

| BUILD_SHARED_LIBS | Build using shared libraries | `ON`, `OFF` | `OFF`
| VISIONARY_SHARED_ENABLE_AUTOIP | Enables the SOPAS Auto-IP device scan code (needs boost's ptree and foreach) |`ON`, `OFF` | `ON`
| VISIONARY_SHARED_ENABLE_UNITTESTS | Enables google-test based unit tests | `ON`, `OFF` | `OFF`
| VISIONARY_SHARED_ENABLE_AUTOIP | Enables the SOPAS Auto-IP device scan code (needs boost's ptree and foreach) | `ON`, `OFF` | `ON`
| VISIONARY_SHARED_USE_BUNDLED_BOOST | Uses the bundled Boost implementation | `ON`, `OFF` | `ON`
|===


== License

The source code is released under link:/LICENSE[The Unlicense].

== Support

Depending on the nature of your request, there are two support channels:

1. For questions regarding the code shared in this repo please check the FAQ first and https://guides.github.com/features/issues/[search if an issue already exists].
   If a related issue doesn't exist, you can open a new issue using the link:.github/issue_form.md[issue form].
2. For application or device specific questions look for common solutions and knowledge articles on the https://support.sick.com/[Sick Support Portal].
   If your question is not answered there, open a ticket on the https://support.sick.com/[Sick Support Portal].
